# Generated by Django 6.0.3 on 2026-03-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('fabric_type', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('uniform', 'Uniform'), ('casual', 'Casual'), ('sportswear', 'Sportswear'), ('workwear', 'Workwear'), ('formal', 'Formal')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('texture', models.ImageField(upload_to='textures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
