# Generated by Django 6.0.3 on 2026-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
